### ISSUE TITLE
Tests failing intermittently in Mir PPA builds

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/wlcs#104]
https://github.com/MirServer/mir/issues/841#issuecomment-503592847

test|comment
---|---
Anchor/XdgPopupPositionerTest.xdg_shell_stable_popup_placed_correctly/4|(Timeout)
ClientSurfaceEventsTest.surface_resizes_under_pointer|(Timeout)
Subsurface/SurfaceTypesWithInputRegion.touch_inside_input_region_is_seen/3|(Timeout)
XdgShellStableSurface/SurfaceTypesWithInputRegion.pointer_seen_entering_and_leaving_input_region/0|(Timeout)

The fact these timeout may well be #89, but I suspect that the failure is probably racy test code.

**Comment by Saviq** [comment]
Haven't seen any of that recently.
