### ISSUE TITLE
Document build instructions and required versions for dependencies ?

### ISSUE THREAD

**Issue by vberger** [MirServer/wlcs#205]
Hi,

I've been willing to toy around with trying to use WLCS for [Smithay](https://github.com/Smithay/smithay), but I fail to compile WLCS on my dev computer, so I suspect I must be doing something wrong, possibly regarding versions of dependencies.

My attempt was:

```
git clone https://github.com/MirServer/wlcs.git
cd wlcs
mkdir build
cd build
cmake ..
make
```

And compilation fails with the following errors:

```
/home/victor/dev/wlcs/tests/pointer_constraints.cpp:47:5: error: reference to ‘Pointer’ is ambiguous
   47 |     Pointer cursor = the_server().create_pointer();
      |     ^~~~~~~
In file included from /home/victor/dev/wlcs/tests/pointer_constraints.cpp:21:
/home/victor/dev/wlcs/include/in_process_server.h:77:7: note: candidates are: ‘class wlcs::Pointer’
   77 | class Pointer
      |       ^~~~~~~
In file included from /usr/include/gmock/gmock-spec-builders.h:75,
                 from /usr/include/gmock/gmock-function-mocker.h:42,
                 from /usr/include/gmock/gmock.h:61,
                 from /home/victor/dev/wlcs/include/pointer_constraints_unstable_v1.h:26,
                 from /home/victor/dev/wlcs/tests/pointer_constraints.cpp:19:
/usr/include/gmock/gmock-matchers.h:4827:47: note:                 ‘template<class InnerMatcher> testing::internal::PointerMatcher<InnerMatcher> testing::no_adl::Pointer(const InnerMatcher&)’
 4827 | inline internal::PointerMatcher<InnerMatcher> Pointer(
      |                                               ^~~~~~~
```

For completeness, the cmake output with the versions of compilers & libraries it found:

```
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3")
-- Performing Test HAVE_W_GNU_VARIADIC_MACROS
-- Performing Test HAVE_W_GNU_VARIADIC_MACROS - Failed
-- Looking for INSTANTIATE_TEST_SUITE_P
-- Looking for INSTANTIATE_TEST_SUITE_P - found
-- Found Boost: /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0")
-- Found GTest: /usr/lib64/cmake/GTest/GTestConfig.cmake (found version "1.11.0")
CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (GMock) does
  not match the name of the calling package (GtestGmock).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindGtestGmock.cmake:60 (find_package_handle_standard_args)
  CMakeLists.txt:62 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found GMock: /usr/include
-- Checking for module 'wayland-client'
--   Found wayland-client, version 1.19.0
-- Checking for module 'wayland-server'
--   Found wayland-server, version 1.19.0
-- Checking for module 'wayland-scanner'
--   Found wayland-scanner, version 1.19.0
-- Found wayland-scanner version 1.19.0, using private-code mode
-- Configuring done
-- Generating done
-- Build files have been written to: /home/victor/dev/wlcs/build
```

**Comment by AlanGriffiths** [comment]
Hi @vberger, this looks like a problem with googlemock/test.

> -- Found GTest: /usr/lib64/cmake/GTest/GTestConfig.cmake (found version "1.11.0")

The Ubuntu archives against which our automated builds run have 1.10, and it appears you are attempting to build with 1.11.

From the error message it appears that 1.11 introduces an ambiguity with `testing::no_adl::Pointer`. It isn't obvious to me why that would be found by name lookup, but a trawl through the gmock headers will likely be informative.

At a guess, replacing the `using namespace testing;` at the head of the file with:
```c++
using testing::AnyNumber;
using testing::NotNull;
using testing::IsTrue;
using testing::_;
```
Will work around this issue.

**Comment by vberger** [comment]
Thanks, changing these, as well as adding `testing::Eq` and `testing::Ne`, in both `tests/relative_pointer.cpp` and `tests/pointer_constraints.cpp` do fix the compilation issues.

However it looks like there is still an issue with the way cmake finds the dependencies: now the compilation fails at link-time with a huge wall of undefined symbols from `testing::internal::`, which I suppose should come from `/usr/lib/libgtest.so` ?

**Comment by AlanGriffiths** [comment]
That sounds like another 1.11 change we've not encountered yet.

The script that attempts to locate the test/mock dependencies is `cmake/FindGtestGmock.cmake` and should be setting `${GMOCK_LIBRARY}` and `${GTEST_LIBRARY}` in the main `CMakeLists.txt`. I'd try dumping those from the latter script with:
```plain
message(STATUS "\GMOCK_LIBRARY=${GMOCK_LIBRARY}")
message(STATUS "\GTEST_LIBRARY=${GTEST_LIBRARY}")
```
to see what is actually being set.

**Comment by vberger** [comment]
Indeed, it looks like something has gone wrong, I get the following in cmake output:

```
GMOCK_LIBRARY=GMock
GTEST_LIBRARY=
```

**Comment by vberger** [comment]
Hmm, so, it looks like I managed to fix the issue by moving the manual setting of `GTEST_LIBRARY` outside of the if/else block it was in, in order for it to be unconditionally executed : 

```diff
diff --git a/cmake/FindGtestGmock.cmake b/cmake/FindGtestGmock.cmake
index a57fed8..359f9ab 100644
--- a/cmake/FindGtestGmock.cmake
+++ b/cmake/FindGtestGmock.cmake
@@ -39,6 +39,12 @@ if (NOT GTEST_FOUND)
     find_package_handle_standard_args(GTest GTEST_LIBRARY GTEST_BOTH_LIBRARIES GTEST_INCLUDE_DIRS)
 endif()

+# Upstream GTestConfig.cmake doesn't provide GTEST_LIBRARY but GTEST_LIBRARIES
+# CMake 3.20+ uses the upstream gtest config if possible.
+if (NOT DEFINED GTEST_LIBRARY)
+    set(GTEST_LIBRARY ${GTEST_LIBRARIES})
+endif()
+
 find_file(GMOCK_SOURCE
         NAMES gmock-all.cc
         DOC "GMock source"
@@ -63,11 +69,6 @@ if (EXISTS ${GMOCK_SOURCE})
 else()
     # Assume gmock is no longer source, we'll find out soon enough if that's wrong
     add_custom_target(GMock)
-    # Upstream GTestConfig.cmake doesn't provide GTEST_LIBRARY but GTEST_LIBRARIES
-    # CMake 3.20+ uses the upstream gtest config if possible.
-    if (NOT DEFINED GTEST_LIBRARY)
-        set(GTEST_LIBRARY ${GTEST_LIBRARIES})
-    endif()
     string(REPLACE gtest gmock GMOCK_LIBRARY ${GTEST_LIBRARY})
 endif()
```

Is this a proper fix, and if so do you want me to make a PR with it, alongside the `using namespace` changes?

**Comment by AlanGriffiths** [comment]
Looking at this `FindGtestGmock.cmake` file, I think it is somewhat of a mess and could do with fixing. (For a start, I don't think we currently have any target systems where `find_package(GTest)` fails. But that's not the immediate problem.

The fix you have looks sensible, so please submit that.

I'd like to treat the name lookup problem separately as, without looking through the gmake 1.11 headers, it isn't clear what's going on. By all means submit a PR for that too, but we may well come up with a cleaner way to address it.

**Comment by AlanGriffiths** [comment]
@wmww do you happen to have a system with gmake 1.11 to hand?
