### ISSUE TITLE
What is the exact goal of this test suite?

### ISSUE THREAD

**Issue by vberger** [MirServer/wlcs#208]
I understand that WLCS we extracted from Mir's test suite. Is its goal to test for Mir's behavior for compositors that would be willing to align themselves on it, or is it to only test the behavior as documented by the protocol XML specifications?

Taking for example the `XdgSurfaceStableTest.gets_configure_event` test, this test creates an `xdg_surface` and expects it to receive an `xdg_surface.configure` event, even though the underlying `wl_surface` is never committed (I checked that through `WAYLAND_DEBUG`). This kind of behavior is not specified in the protocol file, which only require that the server sends a configure event after the client has assigned a role (`xdg_toplevel` or `xdg_popup`) to the surface, and committed it.

So as far as I can tell, this test is testing for some Mir-specific behavior, that is not mandated by the protocol specification. Is this expected?

Note that while I took this test as an example, my question relates to WLCS as a whole, not that only test.

**Comment by AlanGriffiths** [comment]
The intention is to test conformance to the standard. I would have no problems with tests that go beyond the protocol text and check for common practice. (As toolkits do depend on such choices.)

As you note the practice falls short of the ideal and we have been lax in ensuring tests for Mir specific behaviours are in the Mir project, not wlcs. That is mostly accidental and should be fixed.

**Comment by RAOF** [comment]
In addition to what Alan has said, a secondary goal is to highlight bits of the *protocol* which are underspecified and for which different compositors may unintentionally make different choices for.

Such choices often get accidentally depended upon by clients, leading to an unspecified de-facto protocol bring established 😀

In the magical future, a compositor would pass WLCS if *and only if* all correctly-written clients will work with that compositor. (In this magical future there would be a parallel test suite that *clients* could run against to verify that they will work against any correctly-written compositor 😉).

**Comment by vberger** [comment]
Ok, thanks for the clarification. We won't be afraid to open issues & PRs when we'll start to seriously try to make smithay compliant then. :+1:
