### ISSUE TITLE
Build fails with libwayland-git in separate prefix

### ISSUE THREAD

**Issue by subdiff** [MirServer/wlcs#213]
I have self-compiled libwayland from git in `/opt`. 

Trying to compile wlcs leads to a lot of these errors:
```
/home/roman/dev/tooling/wlcs/build/generated/xdg-shell-client.h: In function ‘void xdg_toplevel_resize(xdg_toplevel*, wl_seat*, uint32_t, uint32_t)’:
/home/roman/dev/tooling/wlcs/build/generated/xdg-shell-client.h:1526:9: error: ‘wl_proxy_marshal_flags’ was not declared in this scope; did you mean ‘wl_proxy_marshal_array’?
 1526 |         wl_proxy_marshal_flags((struct wl_proxy *) xdg_toplevel,
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         wl_proxy_marshal_array
```

I've experienced this build failure after the relevant change in libwayland had landed already with some test in Wrapland. The problem there was that the libwayland dependency [was not correctly transitively forwarded](https://gitlab.com/kwinft/wrapland/-/commit/01b08381d3c7e61bc72bfc756940e1dc1dfb90da) in the CMake code. Maybe the solution for wlcs is similar?

**Comment by AlanGriffiths** [comment]
@subdiff thanks for flagging this. We're not normally working with libwayland from git so it may be some time before we are in a position to address this. But if you can provide a fix, we'll happily take it.

**Comment by wmww** [comment]
It looks like `wl_proxy_marshal_flags()` was introduced recently in [this commit](https://github.com/wayland-project/wayland/commit/23e4a7060080ebb61f516a2edcd71ab123029c0e). My guess as to what's going on is that you're using a newer wayland-scanner than libweayland. This results in generated code being incompatible with the wayland-client headers it includes. Perhaps you haven't set `PKG_CONFIG_PATH` to point to the Wayland client library you think you're using?
