### ISSUE TITLE
WLCS will happily bind a global version higher than the one defined in the wayland.xml it was compiled for

### ISSUE THREAD

**Issue by vberger** [MirServer/wlcs#234]
We stumbled on this by chance when working on Smithay's test suite.

In our case, the wayland.xml used to compile Smithay and the one used by WLCS are apparently different (I guess WLCS uses the system one), and while Smithay advertises wl_output version 4, the wayland.xml WLCS was compiled against only has version 3.
Yet, WLCS will bind version 4 of the global, and then libwayland chockes when it receives a `wl_output.name` event which only exists since version 4.

**Comment by wmww** [comment]
I'll take a look

**Comment by Drakulix** [comment]
This is now fixed for optional protocols bound via `bind_if_supported`, but not for core protocols wlcs binds unconditionally via [`global_handler`](https://github.com/MirServer/wlcs/blob/caa368e1d4f45974c61721896ec6ccf2f88712ef/src/in_process_server.cpp#L1480).

So this problem still persists in smithay for `wl_output`. Please reopen.

**Comment by AlanGriffiths** [comment]
> not for core protocols wlcs binds unconditionally via [`global_handler`](https://github.com/MirServer/wlcs/blob/caa368e1d4f45974c61721896ec6ccf2f88712ef/src/in_process_server.cpp#L1480).

Agreed

**Comment by Drakulix** [comment]
Thanks for dealing with this so quickly!
