### ISSUE TITLE
xdg_shell_unstable_v6 is currently not optional in the test suite

### ISSUE THREAD

**Issue by vberger** [MirServer/wlcs#237]
I'm currently trying to expand the set of WLCS tests we run on Smithay, and it appears that many tests involving `xdg_shell_unstable_v6` will fail if the global is missing, even if the global is not listed as a `supported_extensions`.

For test groups like `XdgSurfaceV6Test.*`, it easy to handle: we just don't run the group.

But several other groups contain V6 tests, for example `AnchorRect/XdgPopupPositionerTest.*` contains some `xdg_shell_unstable_v6_popup_placed_correctly/*` test, which currently fail on Smithay because we've dropped `xdg_shell_unstable_v6` support.

It would be very convenient if those tests could be skipped instead if `zxdg_shell_v6` is not listed as part of `supported_extensions`.

I can try to make a PR for this if you don't have time for it, but I'll need some guidance on how to do it properly.

**Comment by AlanGriffiths** [comment]
@vberger I'll try to find time to write down a bit more detail. But wlcs will "xfail" any tests that throw an `ExtensionExpectedlyNotSupported` exception. (And gtest reports that as "SKIPPED")

We should probably be reporting the missing global with `ExtensionExpectedlyNotSupported`.

Note: There should also be a check whether extensions listed in `supported_extensions` are actually supported (not checked that there is). But if the extension is in neither place should not be failing.

**Comment by AlanGriffiths** [comment]
@vberger there was a similar issue with `wl_shell` earlier this year and a similar fix.

If you look in `in_process_server.cpp` you'll find that `wl_shell* the_shell() const` has logic to check `supported_extensions` when `shell` is NULL.

The same is needed in `zxdg_shell_v6* the_xdg_shell_v6() const` (with a check for "zxdg_shell_v6", naturally).
