### ISSUE TITLE
Missing frame callback in frame_timestamp_increases

### ISSUE THREAD

**Issue by bwidawsk** [MirServer/wlcs#292]
I've been looking at improving the test coverage in Smithay and just trying to fix failures one by one. For frame_timestamp_increases it appears that only one `frame` request is issued, yet the test expects >= 2 (and why it's not == 2 is kind of sad as well). The proper fix should be to emit two `frame` requests and have a wait for the first to complete before emitting the second.

**Comment by AlanGriffiths** [comment]
This sounds right. From the documentation of `wl_surface_frame()`:

```plain
 * The frame request will take effect on the next wl_surface.commit.
 * The notification will only be posted for one frame unless
 * requested again.
```

> and why it's not == 2 is kind of sad as well

Testing for exactly two frames is a valid thing to test, but it could be misleading if `frame_timestamp_increases` fails for this reason.
