### ISSUE TITLE
v1.6.0 not marked as "release" on GitHub

### ISSUE THREAD

**Issue by z3ntu** [MirServer/wlcs#303]
It's only a tag so it doesn't show up on https://github.com/MirServer/wlcs/releases

Also not sure, but with 1.4.0 a `wlcs-1.4.0.tar.xz` + gpg signature was attached, is this missing on purpose for 1.5.0 also?

**Comment by Saviq** [comment]
Thanks @z3ntu for noticing, things should be in order now:

https://github.com/MirServer/wlcs/releases/

Needed a 1.6.1 to fix the version number in CMake (and so 1.6.0 _doesn't_ have a tarball).

**Comment by z3ntu** [comment]
Thanks for the quick resolution!
