### ISSUE TITLE
XDG configure event expected without commit

### ISSUE THREAD

**Issue by bwidawsk** [MirServer/wlcs#312]
https://wayland.app/protocols/xdg-shell#xdg_surface

> For an xdg_surface to be mapped by the compositor, the following conditions must be met: (1) the client has assigned an xdg_surface-based role to the surface (2) the client has set and committed the xdg_surface state and the role-dependent state to the surface (3) the client has committed a buffer to the surface

Tests such as XdgSurfaceStableTest.gets_configure_event do not actually commit while expecting configure.

Something like the following should make correct compositors pass:
``` diff
diff --git a/tests/xdg_surface_stable.cpp b/tests/xdg_surface_stable.cpp
index c0a543777a1a..2b50389724cb 100644
--- a/tests/xdg_surface_stable.cpp
+++ b/tests/xdg_surface_stable.cpp
@@ -58,6 +58,7 @@ TEST_F(XdgSurfaceStableTest, gets_configure_event)
         });

     wlcs::XdgToplevelStable toplevel{xdg_surface};
+    wl_surface_commit(surface);
     surface.attach_buffer(600, 400);

     client.roundtrip();
```

**Comment by AlanGriffiths** [comment]
I don't disagree with your conclusion, but I think the correct reference is:

> After creating a role-specific object and setting it up, the client must perform an initial commit without any buffer attached. The compositor will reply with initial wl_surface state such as wl_surface.preferred_buffer_scale followed by an xdg_surface.configure event.

_(ibid)_
